### ISSUE TITLE
Issue with missing selector

### ISSUE THREAD

**Issue by jenn-sweet** [jenn-sweet/use-all-the-selectors#1]
<img width="418" alt="Screen Shot 2021-03-11 at 8 35 20 PM" src="https://user-images.githubusercontent.com/77341921/110878712-b0123800-82a9-11eb-991f-ae0c7c884a70.png">

I have no idea what selector it is looking for : /

@hellachella

**Comment by hellachella** [comment]
You are missing the second half of your boilerplate CSS.

```
*, *::before, *::after {
  box-sizing: inherit;
}
```
Add this underneath the HTML selector set

**Comment by jenn-sweet** [comment]
OMG!
Thank you! I was going through alllllll the other selectors line by line and did not even think about the boilerplate  : |

**Comment by hellachella** [comment]
pls close this issue
